baseURL = "https://TG-Bao.github.io/TGB_Blog/"
languageCode = "vi"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang chủ"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Bài viết"
    url = "/posts/"
    weight = 2
